name: node.js
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
        env: 
          CI: ""